_6tactics.Cms.Web/Controllers/WebController.cs
using _6tactics.Cms.Core.Attributes;
using _6tactics.Cms.Services.Web;
using _DataAccess.UnitOfWork;
using System.Web.Mvc;

namespace _6tactics.Cms.Web.Controllers
{
    public class WebController : BaseWebController
    {
        public WebController(IUnitOfWork unitOfWork, ISeoDataService seoData, ISiteMapService siteMap)
        {
            SiteMap = siteMap;
            Uof = unitOfWork;
            SeoDataService = seoData;
        }

        [Route("robots.txt", Name = "GetRobotsText"), OutputCache(Duration = 21600)] // 6h
        public new ContentResult RobotsText()
        {
            return base.RobotsText();
        }

        [Route("sitemap.xml", Name = "GetSitemapXml"), OutputCache(Duration = 21600)] // 6h
        public new ContentResult SitemapXml()
        {
            return base.SitemapXml();
        }

        public new ActionResult GetFile(string folderPath, string filename, string extensionName)
        {
            return base.GetFile(folderPath, filename, extensionName);
        }

        [ChildActionOnlyCustom]
        public new PartialViewResult SeoData()
        {
            return base.SeoData();
        }

        public new ActionResult Index(string lang, string routeTitle)
        {
            return base.Index(lang, routeTitle);
        }
    }
}

_6tactics.Cms.Web/Views/Shared/Web/_FilesForDownload.cshtml
@using _6tactics.Utilities.Web
@model _6tactics.Cms.Core.ViewModels.Web.SectionViewModel

@foreach (var item in Model.Items)
{
    if (!string.IsNullOrWhiteSpace(item.FileUrl))
    {
        <div class="col-md-6">
            <div class="tip"><div title="file for download" class="tip-cube-icon"></div><a href="@FileUrlBuilder.CreateUrl(string.Concat("content/uploads/", item.Id.ToString()), item.FileUrl)">@item.Title</a></div>
        </div>
    }
}

_6tactics.Cms.Web/Views/Shared/Web/_Footer.cshtml
@using _6tactics.Cms.Core.Enums.Admin
@model _6tactics.Cms.Core.ViewModels.Web.PageViewModel

@if (Model.FooterSections != null)
{
    <footer>
        <div>
            @foreach (var item in Model.FooterSections)
            {
                if (item.ContentType == ContentType.ContentElement)
                {
                    string linkStyle = "";
                    if (item.DisplayType == "LinkWithImage" || item.DisplayType == "LinkWithTitle" || item.DisplayType == "LinkWithTitleAndImage")
                    {
                        linkStyle = "text-align: center;";
                    }
                    <div class="row section-row-footer" style="@linkStyle">
                        @Html.Partial("~/Views/Shared/Web/_SectionViewContentElement.cshtml", item)
                    </div>
                }
            }
            <div class="footer-text">
                @Model.Project.Title &copy; @DateTime.Now.Year
            </div>
        </div>
    </footer>
}

_6tactics.Cms.Web/Views/Shared/Web/_FooterFixed.cshtml
@using _6tactics.Cms.Core.Enums
@using _6tactics.Cms.Core.Enums.Admin
@using _6tactics.Cms.Web.App_Logic
@model _6tactics.Cms.Core.ViewModels.Web.PageViewModel


<div class="fixed-space-before-footer"></div>

<footer class="navbar-fixed-bottom">
    <div>
        @* ne prikazati title ako nije dozvoljeno! *@

        @if (Model.FooterSections != null)
        {
            foreach (var item in Model.FooterSections)
            {
                if (item.ContentType == ContentType.ContentElement
                    && ElementsVisibilityUtility.IsSectionVisible(item.ElementVisibility, User.Identity.IsAuthenticated, item.Items.ToList()))
                {
                    string linkStyle = "";
                    if (item.DisplayType == "LinkWithImage" || item.DisplayType == "LinkWithTitle" || item.DisplayType == "LinkWithTitleAndImage")
                    {
                        linkStyle = "text-align: center;";
                    }

                    <div class="row section-row-footer" style="@linkStyle">
                        @* ne prikazati title ako nije dozvoljeno! *@
                        @if (ElementsVisibilityUtility.IsSectionTitleVisible(item.SectionTitleVisibility))
                        {
                            <p class="section-title-footer">@item.Title</p>
                        }
                        @Html.Partial("~/Views/Shared/User/_SectionView.cshtml", item)
                    </div>
                }
            }
        }

        <div class="footer-text">
            @Model.Project.Title.ToUpper() &copy; @DateTime.Now.Year
        </div>
    </div>
</footer>

_6tactics.Cms.Web/Views/Shared/Web/_MainMenu.cshtml
@using _6tactics.Cms.Core.Enums
@using _6tactics.Cms.Core.Enums.Admin
@using _6tactics.Cms.Web.App_Logic
@using _6tactics.Utilities.Common
@using _6tactics.Utilities.Web.Helpers.String
@model _6tactics.Cms.Core.ViewModels.Web.PageViewModel

@{
    //string currentPage = Model.PageContentMenu.Title;
    //var pagePath = new PagePathBuilder(ElementsVisibilityUtility.CurrentLanguage, Model.MainMenu.Items);
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            @if (CheckExistence.IsUrlExist(Model.Project.FileUrl))
            {
                <a href="#home" rel="" class="logo-small"><img src="@Model.Project.FileUrl" alt="logo-small"></a>
            }

        </div>
        @*<div class="navbar-collapse collapse navbar-example">*@
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @{
                    var firstOrDefaultLanguage = Model.LanguagesWithDefaultRouteTitle.FirstOrDefault();
                    var languageFromRouteData = HttpContext.Current.Request.RequestContext.RouteData.Values["lang"];
                    var selectedLanguage = languageFromRouteData ?? firstOrDefaultLanguage;

                    // List page links
                    if (Model.MainMenu.Items.ToList().Count > 1)
                    {
                        foreach (var item in Model.MainMenu.Items)
                        {
                            // Add for visibility hidden
                            <li><a href="@Url.Action("Index", "Web", new { lang = selectedLanguage, pageId = item.Id })">@item.Title</a></li>
                        }
                    }

                    // List section titles
                    else
                    {
                        foreach (var item in Model.PageContentMenu.Items
                            .Where(item => item.SectionTitleVisibility != null && item.SectionTitleVisibility != SectionTitleVisibility.Hidden))
                        {
                            if (ElementsVisibilityUtility.IsSectionVisible(item.ElementVisibility, User.Identity.IsAuthenticated, Model.PageContentMenu.Items.ToList()))
                            {
                                <li><a href="#@Html.WordsConnecting(item.Title)">@item.Title</a></li>
                            }
                        }
                    }
                }

            </ul>
            <ul class="nav navbar-nav navbar-right">

                @* List languages *@
                @if (Model.LanguagesWithDefaultRouteTitle.Count > 1)
                {
                    foreach (var language in Model.LanguagesWithDefaultRouteTitle)
                    {
                        //if (Model.PageContentMenu.Items.Where(i => i.ContentType == ContentType.Language && i.Title == language))
                        <li><a href="@Url.Action("Index", "Web", new { lang = language })">@language</a></li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

@*<div class="container-fluid selected-page-panel">d
    <div class="wrapper">
        <div class="pull-left selected-page">@currentPage</div>
        <div class="pull-right selected-page-path">@pagePath.GetPagePath</div>
    </div>
    <div class="empty-row"></div>
</div>*@

<a name="home" id="home"></a>

<script type="text/javascript">
    $(function () {

        $(window).on("load", function () {
            $("body").css("margin-top", $(".navbar").height() - 48);
        });

        $(window).on("resize", function () {
            $("body").css("margin-top", $(".navbar").height() - 48);
        });

        //$('.toresponsive').resmenu({ maxWidth: 850 }).resmenuBootstrap();
        $('.toresponsive').resmenu({ maxWidth: 860 });

        //$('.navbar').animatedScrollNavigation({ menuItemSelectingType: 'immediately' });
        $('.navbar').animatedScrollNavigation({ menuItemSelectingType: 'onScroll' });
        //$('.navbar').animatedScrollNavigation();

    });
</script>

_6tactics.Cms.Web/Views/Shared/Web/_MainMenuDropDown.cshtml
@using _6tactics.Cms.Core.Enums.Admin
@using _6tactics.Cms.Core.Models.Common
@using _6tactics.Cms.Web.App_Logic
@using _6tactics.Cms.Web.Helpers
@using _6tactics.Utilities.Web.Helpers.String
@model _6tactics.Cms.Core.ViewModels.Web.PageViewModel

@{
    string firstOrDefaultLanguage = Model.LanguagesWithDefaultRouteTitle.Keys.FirstOrDefault();
    string languageFromRouteData = ElementsVisibilityUtility.CurrentLanguage;
    string selectedLanguage = languageFromRouteData ?? firstOrDefaultLanguage;

    string currentPage = Model.PageContentMenu.Title;
    var pagePath = new PagePathBuilder(ElementsVisibilityUtility.CurrentLanguage, Model.MainMenu.Items);

    bool isMenuHasMultiplePages = Model.MainMenu.Items.Count() > 1
     || Model.MainMenu.Items.ToList().Find(i => i.ContentType == ContentType.Page).ContentItems.Count(i => i.ContentType == ContentType.Page) >= 1;
}

@helper MenuBuilder(string selectedLanguage, IEnumerable<IContentItem> contentItems)
{
    foreach (var page in contentItems.Where(item => item.ContentType == ContentType.Page && item.ElementVisibility != ElementVisibility.Hidden).OrderBy(i => i.Priority))
    {
        var selectedClass = ElementsVisibilityUtility.IsPageSelected(page, ElementsVisibilityUtility.CurrentRouteTitle) ? "selected" : "";
            <li style="color: white" class="@selectedClass">
                @if (page.ContentItems.Count(i => i.ContentType == ContentType.Page) > 0)
                {
                    var isParentContentTypePage = page.Parent.ContentType == ContentType.Page;
                    var submenuClass = isParentContentTypePage ? "submenu" : "";

                    if (isParentContentTypePage)
                    {
                        <a href="@Url.Action("index", "web", new {lang = selectedLanguage, routeTitle = page.RouteTitle})"><i class="left-arrow fa fa-caret-left"></i> @page.Title <i class="right-arrow fa fa-caret-right"></i></a>
                    }
                    else
                    {
                        <a href="@Url.Action("index", "web", new {lang = selectedLanguage, routeTitle = page.RouteTitle})"> @page.Title <i class="fa fa-caret-down"></i></a>
                    }
                    <ul class="@submenuClass">@MenuBuilder(selectedLanguage, page.ContentItems)</ul>
                }
                else
                {
                    <a href="@Url.Action("index", "web", new {lang = selectedLanguage, routeTitle = page.RouteTitle})">@page.Title</a>
                }
            </li>
    }
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

        <div style="margin: 0 auto" class="row">

            <div class="col-md-3 header-logo-wrapper">
                @{var fileUrlHelper = new FileUrlHelper(Model.Project.FileUrl);}
                @if (fileUrlHelper.IsUrlValid)
                {
                    // If is single page do scroll with animation on first item
                    if (Model.LanguagesWithDefaultRouteTitle.Count < 1)
                    {
                        <a href="#home" rel=""><img src="@Url.Action("GetFile", "Web", new { folderPath = fileUrlHelper.RouteFolderPath, filename = fileUrlHelper.Filename, extensionName = fileUrlHelper.ExtensionName})" alt="logo"></a>
                    }
                    // If is multiple page website goto home page
                    else
                    {
                        <a href="@Url.Action("index", "web", new {lang = ElementsVisibilityUtility.CurrentLanguage, routeTitle = "", area = ElementsVisibilityUtility.GetCurrentArea(Request)})" rel="">
                            <img src="@Url.Action("GetFile", "Web", new { folderPath = fileUrlHelper.RouteFolderPath, filename = fileUrlHelper.Filename, extensionName = fileUrlHelper.ExtensionName})" alt="logo">
                        </a>
                    }
                }
            </div>

            <div class="col-md-9 header-menu-wrapper">

                @if (Model.LanguagesWithDefaultRouteTitle.Count > 1)
                {
                    @* List languages with default route value*@
                foreach (var languageWithDefaultRouteTitle in Model.LanguagesWithDefaultRouteTitle.Reverse())
                {
                    var textTransform = "none";
                    if (selectedLanguage != null && selectedLanguage.Equals(languageWithDefaultRouteTitle.Key, StringComparison.InvariantCultureIgnoreCase))
                    {
                        textTransform = "underline!important";
                    }
                    <a style="text-decoration: @textTransform" class="dropdown-menu-language-list" href="@Url.Action("index", "web", new {lang = languageWithDefaultRouteTitle.Key, routeTitle = languageWithDefaultRouteTitle.Value, area = ElementsVisibilityUtility.GetCurrentArea(Request)})">
                        @languageWithDefaultRouteTitle.Key.ToUpper()
                    </a>
                    }
                }

                <div style="margin-top: 30px;" class="menus_wrapper">

                    <ul class="list-menu">
                        @{
                            // List page links hierarchically
                            if (isMenuHasMultiplePages)
                            {
                                @MenuBuilder(selectedLanguage, Model.MainMenu.Items)
                            }

                            // If page count is 1 list section titles (as singe page web)
                            else
                            {
                                foreach (var item in Model.PageContentMenu.Items
                                    .Where(item => item.SectionTitleVisibility != null && item.SectionTitleVisibility != SectionTitleVisibility.Hidden)
                                    .Where(item => ElementsVisibilityUtility.IsSectionVisible(item.ElementVisibility, User.Identity.IsAuthenticated, Model.PageContentMenu.Items.ToList())))
                                {
                                    <li><a href="#@Html.WordsConnecting(item.Title)">@item.Title</a></li>
                                }
                            }
                        }
                    </ul>

                </div>

            </div>

        </div>
    </div>
</div>

<div class="container-fluid selected-page-panel">
    <div class="web-current-location-wrapper wrapper">
        <div class="selected-page"><h1 style="font-size: 1em; margin: 0; margin-top: 2px;">@currentPage</h1></div>
        <div class="selected-page-path">@pagePath.GetPagePath</div>
    </div>
</div>

<a id="home"></a>

<script type="text/javascript">
    $(function () {
        var onWhichSizeOpensTheDropDownMenu = 860;

        $('.list-menu').resmenu({ maxWidth: onWhichSizeOpensTheDropDownMenu, menuActualWidthTolerance: 5 });
        $('.selected-page-panel').selectedPagePanel({ onWhichSizeHideTitle: onWhichSizeOpensTheDropDownMenu });
    });
</script>

@* Add animatedScrollNavigation for single page web *@
@if (!isMenuHasMultiplePages)
{
    <script type="text/javascript">
        $(function () {
            $('.navbar').animatedScrollNavigation({ menuItemSelectingType: 'onScroll' });

            // napraviti tako da bude samo jedan plugin, da se odlucuje kada se na koji ide
            //$('#dropdown-menu1').animatedScrollNavigation();
        });
    </script>
}

_6tactics.Cms.Web/Views/Shared/Web/_PageContentMenu.cshtml
@using _6tactics.Utilities.Web.Helpers.String
@model _6tactics.Cms.Core.ViewModels.Web.SectionViewModel

<ul id="navigation">
    @foreach (var item in Model.Items)
    {
        // Add for visibility hidden 
        <li class="home"><a href="#@Html.WordsConnecting(item.Title)">@item.Title</a></li>
    }
</ul>

<script type="text/javascript">
    $(function () {
        $('#navigation a').stop().animate({ 'marginLeft': '-20px' }, 1000);

        $('#navigation > li').hover(
            function () {
                $('a', $(this)).stop().animate({ 'marginLeft': '-2px' }, 200);
            },
            function () {
                $('a', $(this)).stop().animate({ 'marginLeft': '-20px' }, 200);
            }
        );
    });
</script>

_6tactics.Cms.Web/Views/Shared/Web/_SectionTitle.cshtml
@using _6tactics.Cms.Web.App_Logic
@using _6tactics.Utilities.Web.Helpers.String
@model _6tactics.Cms.Core.ViewModels.Web.SectionViewModel

@if (ElementsVisibilityUtility.IsSectionTitleVisible(Model.SectionTitleVisibility))
{
    <div class="col-md-12 row-headline scrollDetector">
        <a id="@Html.WordsConnecting(Model.Title)">@Model.Title</a>
    </div>
}

_6tactics.Cms.Web/Views/Shared/Web/_SectionViewFile.cshtml
@using _6tactics.Cms.Web.App_Logic
@model _6tactics.Cms.Core.ViewModels.Web.SectionViewModel

@{
    var bootstrapUnpredictableHeight = new BootstrapUnpredictableHeight();
}

@foreach (var item in Model.Items.OrderBy(i => i.Priority).ThenBy(i => i.Id))
{

    switch (item.DisplayType)
    {
        case "ImageFluid":
            @Html.Partial("~/Views/Shared/DisplayTypes/_ImageFluid.cshtml", item)
            break;
        case "Image":
            <div class="@item.Parent.ElementWidth @BootstrapUnpredictableHeight.ClearBothClassHandler(bootstrapUnpredictableHeight, item.DisplayType, item.Parent.ElementWidth)">
                @Html.Partial("~/Views/Shared/DisplayTypes/_Image.cshtml", item)
            </div>
            break;
        case "FilesForDownload":
            @Html.Partial("~/Views/Shared/DisplayTypes/_FilesForDownload.cshtml", item)
            break;
        case "ImageSlider":
            @Html.Partial("~/Views/Shared/DisplayTypes/_ImageSlider.cshtml", item)
            break;
        case "ImageGallery":
            <div class="@item.Parent.ElementWidth @BootstrapUnpredictableHeight.ClearBothClassHandler(bootstrapUnpredictableHeight, item.DisplayType, item.Parent.ElementWidth)">
                @Html.Partial("~/Views/Shared/DisplayTypes/_ImageGallery.cshtml", item)
            </div>
            break;
    }
}

_6tactics.Cms.Web/Views/Shared/Web/_SectionViewHome.cshtml
@using _6tactics.Cms.Core.Enums.Admin
@using _6tactics.Cms.Web.Helpers
@model _6tactics.Cms.Core.ViewModels.Web.PageViewModel

@foreach (var item in Model.PageSections)
{
    if (item.ContentType == ContentType.FileElement)
    {
        if (item.DisplayType.Equals("ImageFluid"))
        {
            <div class="container-fluid" style="padding: 0!important;">
                @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)
                @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
            </div>
        }
        else if (item.DisplayType.Equals("Image"))
        {
            <div class="container">
                <div class="row">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)
                    @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
                </div>
            </div>
        }
        else if (item.DisplayType.Equals("ImageSlider"))
        {
            <div class="container">
                <div class="row">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)

                    <div class="image-slider owl-carousel owl-theme">
                        @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
                    </div>
                </div>
            </div>
        }
        else if (item.DisplayType.Equals("ImageGallery"))
        {
            <div class="container">
                <div class="row">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)

                    <div id="image-@item.Id" class="popup-gallery">
                        @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
                    </div>
                </div>
            </div>
        }
        else if (item.DisplayType.Equals("FilesForDownload"))
        {
            <div class="container">
                <div class="row text-center margin-bottom-20px">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)
                    @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
                </div>
            </div>
        }
        else
        {
            <div class="container">
                <div class="row">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)
                    @Html.Partial("~/Views/Shared/Web/_SectionViewFile.cshtml", item)
                </div>
            </div>
        }
    }
    else if (item.ContentType == ContentType.ContentElement)
    {
        string linkStyle = "";
        if (item.DisplayType == "LinkWithImage" || item.DisplayType == "LinkWithTitle" || item.DisplayType == "LinkWithTitleAndImage")
        {
            linkStyle = "text-center margin-bottom-20px";
        }

        if (item.DisplayType == "ParallaxSliderFluid")
        {
            @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)

            var fileUrlHelper = new FileUrlHelper(item.FileUrl);

            <div class="container-fluid" style="padding: 0;">
                <div id="da-slider" class="da-slider" style="background: transparent url(@Url.Action("GetFile", "Web", new { folderPath = fileUrlHelper.RouteFolderPath, filename = fileUrlHelper.Filename, extensionName = fileUrlHelper.ExtensionName })) repeat 0 0;">
                    @Html.Partial("~/Views/Shared/Web/_SectionViewContentElement.cshtml", item)

                    @*  Navigation *@
                    <nav class="da-arrows">
                        <i class="da-arrows-prev fa fa-angle-left"></i>
                        <i class="da-arrows-next fa fa-angle-right"></i>
                    </nav>
                </div>
            </div>
        }
        else if (item.DisplayType == "GoogleMapFluid")
        {
            @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)

            <div class="container-fluid" style="padding: 0!important;">
                @Html.Partial("~/Views/Shared/Web/_SectionViewContentElement.cshtml", item)
            </div>
        }
        else if (item.DisplayType == "EmptyRow" && item.ElementVisibility == ElementVisibility.Visible)
        {
            @Html.Partial("~/Views/Shared/DisplayTypes/_EmptyRow.cshtml")
        }
        else if (item.DisplayType == "CubeLink")
        {
            <div class="container">

                <div class="row margin-bottom-40px">

                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)

                    <div class="col-md-12">
                        <div id="grid-container" style="clear: both;">
                            <ul>
                                @Html.Partial("~/Views/Shared/Web/_SectionViewContentElement.cshtml", item)
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container">
                <div class="row @linkStyle">
                    @Html.Partial("~/Views/Shared/Web/_SectionTitle.cshtml", item)
                    @Html.Partial("~/Views/Shared/Web/_SectionViewContentElement.cshtml", item)
                </div>
            </div>
        }
    }
}