_6tactics.Cms.Web/Controllers/AdminController.cs
using _6tactics.Cms.Core.Attributes;
using _6tactics.Cms.Core.Entities;
using _6tactics.Cms.Core.Enums.Admin;
using _6tactics.Cms.Core.Utilities;
using _6tactics.Cms.Core.ViewModels.Admin;
using _6tactics.Cms.Services.Admin;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace _6tactics.Cms.Web.Controllers
{
    [Authorizer(Roles = "Administrators,AdminReadOnly")]
    public class AdminController : Controller
    {

        #region Fields

        private readonly IAdminLogicService _adminLogicService;
        private readonly IAdminViewModelBuilderService _adminViewModelBuilderService;

        #endregion


        #region Constructors

        public AdminController(
            IAdminLogicService adminService,
            IAdminViewModelBuilderService adminViewModelBuilderService)
        {
            _adminLogicService = adminService;
            _adminViewModelBuilderService = adminViewModelBuilderService;
        }

        #endregion


        #region Index

        public ActionResult Index(string lang, int? pageId)
        {
            return CreateIndexAndPrioritiesView(lang, pageId);
        }


        #endregion


        //#region Details

        //public ActionResult Details(int? id)
        //{
        //    AdminActionsViewModel viewModel = _adminViewModelBuilderService.CreateAdminActionsViewModel(id, ContentItemAction.Details);

        //    if (id == null || viewModel.ContentItemModel == null) return RedirectToAction("Index");

        //    return View(viewModel);
        //}

        //#endregion


        #region Create

        public ActionResult Create(int? parentId, string language = null)
        {
            if (parentId == null) return RedirectToAction("Index");

            AdminActionsViewModel viewModel = _adminViewModelBuilderService.CreateAdminActionsViewModel(parentId, ContentItemAction.Create, language);

            return View(viewModel);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ValidateInput(false), ValidateAntiForgeryToken]
        public ActionResult Create(AdminActionsViewModel model, HttpPostedFileBase file)
        {
            if (model.ContentItemViewModel.LinkOption != LinkOption.Custom)
                ModelState.Remove("ContentItemViewModel.LinkTo");

            // Checking is modelstate valid
            if (!ModelState.IsValid)
            {
                PopupMessageUtility.SetMessage(ContentItemAction.ModelState, MessageType.Error);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.ParentId,
                         ContentItemAction.Create, model.CreateEditDataViewModel.ElementLanguage));
            }

            // Check if child element with same name under current language exist
            if (_adminLogicService.IsChildElemetnWithSameNameExist(model) || _adminLogicService.IsPageWithSameNameUnderSelectedLanguageExist(model))
            {
                PopupMessageUtility.SetMessage(ContentItemAction.AlreadyExistInDbOnCreate, MessageType.Warning);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.ParentId,
                            ContentItemAction.AlreadyExistInDbOnCreate, model.CreateEditDataViewModel.ElementLanguage));
            }

            // Check if footer under current language exist
            if (_adminLogicService.IsFooterUnderSameLanguageExist(model))
            {
                PopupMessageUtility.SetMessage(ContentItemAction.FooterUnderLanguageAlreadyExistOnCreate, MessageType.Warning);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.ParentId,
                            ContentItemAction.FooterUnderLanguageAlreadyExistOnCreate, model.CreateEditDataViewModel.ElementLanguage));
            }

            ContentItem contentItem = _adminLogicService.MapAndSaveAndReturnContentItem(model);

            var redirectionId = _adminLogicService.GetRedirectionId(model, contentItem);

            if (redirectionId != null)
            {
                PopupMessageUtility.SetMessage(ContentItemAction.Create, MessageType.Success);
                return RedirectToAction("Create", new { parentId = redirectionId });
            }

            PopupMessageUtility.SetMessage(ContentItemAction.Create, MessageType.Success);


            return RedirectToAction("Index");
        }

        #endregion


        #region Edit

        public ActionResult Edit(int? id, string language = null)
        {
            if (id == null) return RedirectToAction("Index");

            AdminActionsViewModel viewModel = _adminViewModelBuilderService.CreateAdminActionsViewModel(id, ContentItemAction.Edit, language);

            if (viewModel.ContentItemViewModel == null) return RedirectToAction("Index");

            return View(viewModel);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ValidateInput(false), ValidateAntiForgeryToken]
        public ActionResult Edit(AdminActionsViewModel adminActionsViewModel, HttpPostedFileBase file)
        {
            var model = adminActionsViewModel;

            if (model.ContentItemViewModel.LinkOption != LinkOption.Custom)
                ModelState.Remove("ContentItemViewModel.LinkTo");

            // Checking is modelstate valid
            if (!ModelState.IsValid)
            {
                PopupMessageUtility.SetMessage(ContentItemAction.ModelState, MessageType.Error);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.Id,
                         ContentItemAction.Edit, model.CreateEditDataViewModel.ElementLanguage));
                //return RedirectToAction("Index");
            }

            // Check if child element with same name under current language exist
            if (_adminLogicService.IsChildElemetnWithSameNameExist(model) || _adminLogicService.IsPageWithSameNameUnderSelectedLanguageExist(model))
            {
                PopupMessageUtility.SetMessage(ContentItemAction.AlreadyExistInDbOnEdit, MessageType.Warning);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.Id,
                            ContentItemAction.AlreadyExistInDbOnEdit, model.CreateEditDataViewModel.ElementLanguage));
            }

            // Check if footer under current language exist
            if (_adminLogicService.IsFooterUnderSameLanguageExist(model))
            {
                PopupMessageUtility.SetMessage(ContentItemAction.FooterUnderLanguageAlreadyExistOnEdit, MessageType.Warning);

                return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.Id,
                            ContentItemAction.FooterUnderLanguageAlreadyExistOnEdit, model.CreateEditDataViewModel.ElementLanguage));
            }

            _adminLogicService.UpdateContentItemAndHisChildren(adminActionsViewModel);

            // Fires success message
            PopupMessageUtility.SetMessage(ContentItemAction.Edit, MessageType.Success);

            return View(_adminViewModelBuilderService.CreateAdminActionsViewModel(model.ContentItemViewModel.Id,
                            ContentItemAction.Edit, model.CreateEditDataViewModel.ElementLanguage));

            //return RedirectToAction("Index");
        }

        #endregion


        #region Priorities

        public ActionResult Priorities(string lang, int? pageId)
        {
            return CreateIndexAndPrioritiesView(lang, pageId);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ActionName("Priorities"), ValidateAntiForgeryToken]
        public ActionResult SetPriorities([Bind(Include = "Id,Priority")] FormCollection formItem)
        {
            if (!ModelState.IsValid)
            {
                PopupMessageUtility.SetMessage(ContentItemAction.ModelState, MessageType.Error);
                return RedirectToAction("Index");
            }

            _adminLogicService.SetPriorities(formItem);

            PopupMessageUtility.SetMessage(ContentItemAction.Priorities, MessageType.Success);
            return RedirectToAction("Index");
        }

        #endregion


        #region Delete

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var dataForDelete = _adminLogicService.GetDataForDelete(id);
            if (dataForDelete == null) return HttpNotFound();

            return PartialView(dataForDelete);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            _adminLogicService.DeleteContentItems(id);

            PopupMessageUtility.SetMessage(ContentItemAction.Delete, MessageType.Success);
            return RedirectToAction("Index");
        }

        #endregion


        #region Dispose

        //protected override void Dispose(bool disposing)
        //{
        //    base.Dispose(disposing);
        //}

        #endregion


        #region Utilities

        private ActionResult CreateIndexAndPrioritiesView(string language, int? pageId)
        {
            AdminActionsViewModel viewModel = _adminViewModelBuilderService
                .CreateAdminActionsViewModel(language, pageId, Server.MapPath("~/Content/Uploads"));

            if (viewModel.ContentItemModel != null) return View(viewModel);

            PopupMessageUtility.SetMessage(ContentItemAction.NewProject, MessageType.Info);
            return RedirectToAction("Index", "Setup");
        }

        #endregion 

    }

}

_6tactics.Cms.Web/Controllers/AjaxController.cs
using _6tactics.Cms.Core.Attributes;
using _6tactics.Cms.Core.Enums.Admin;
using _6tactics.Cms.Core.Helpers;
using _6tactics.Cms.Core.ViewModels.Admin;
using _6tactics.Cms.Services.Common;
using _6tactics.SimpleCaptcha;
using _DataAccess.Repositories;
using System.Linq;
using System.Web.Mvc;

namespace _6tactics.Cms.Web.Controllers
{
    [AjaxOnly]
    public class AjaxController : Controller
    {
        private readonly IContentItemRepository _contentItemRepository;
        private readonly IContentItemsWithParentCountService _contentItemsWithParentCount;

        public AjaxController(IContentItemRepository contentItemRepository, IContentItemsWithParentCountService contentItemsWithParentCount)
        {
            _contentItemRepository = contentItemRepository;
            _contentItemsWithParentCount = contentItemsWithParentCount;
        }

        public JsonResult GetDisplayTypeList(ContentType selectedContentType)
        {
            return Json(DisplayTypeSelectorHelper.DisplayTypesForEditPage(selectedContentType), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLanguages()
        {
            return Json(_contentItemRepository.LanguageList.ToList(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult PagesBySelectedLanguage(string selectedLanguage, string currentAction)
        {
            return PartialView(new AdminPagesListViewModel
            {
                SelectedLanguage = selectedLanguage,
                CurrentAction = currentAction,
                ElementsDepthAndTitle = _contentItemsWithParentCount
                .GetFiltered(i => i.ContentType == ContentType.Page, _contentItemRepository.GetLanguageItemByTitle(selectedLanguage).ContentItems)
            });
        }

        public JsonResult IsCaptchaValid(string captchaFor, string solution)
        {
            string solutionFixedData = string.IsNullOrWhiteSpace(solution) ? "22" : solution;
            bool isCaptchaValid = SimpleCaptcha.Utilities.IsCaptchaValid(solutionFixedData, SimpleCaptchaInitializer.CurrentCaptcha[captchaFor]);

            return Json(isCaptchaValid, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RegenerateCaptcha(string captchaFor)
        {
            return Json(new SimpleCaptchaInitializer().GenerateCaptchaString(captchaFor), JsonRequestBehavior.AllowGet);
        }
    }
}

_6tactics.Cms.Web/Controllers/PluginsManagerController.cs
using _6tactics.Cms.Core.Attributes;
using _6tactics.Cms.Services.Plugins;
using System.Web.Mvc;

namespace _6tactics.Cms.Web.Controllers
{
    [Authorizer(Roles = "Administrators,AdminReadOnly")]
    public class PluginsManagerController : Controller
    {
        #region Fields

        private readonly IPluginsManagerService _pluginsHandlerService;

        #endregion


        #region Constructors

        public PluginsManagerController(IPluginsManagerService pluginsHandlerService)
        {
            _pluginsHandlerService = pluginsHandlerService;
        }

        #endregion


        public ActionResult Index()
        {
            return View(_pluginsHandlerService.GetListOfPluginsWithActions());
        }


        [AjaxOnly]
        public PartialViewResult PluginActions(string pluginName)
        {
            return PartialView(_pluginsHandlerService.GetPluginActions(pluginName));

        }
    }
}

_6tactics.Cms.Web/Controllers/RolesAdministrationController.cs
using _6tactics.AspIdentity.Repositories;
using _6tactics.AspIdentity.ViewModels.RolesHandler;
using _6tactics.Cms.Core.Attributes;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace _6tactics.Cms.Web.Controllers
{
    [Authorizer(Roles = "Administrators,AdminReadOnly")]
    public class RolesAdministrationController : IdentityBaseController
    {
        #region Constructors

        public RolesAdministrationController(IIdentityRepository identityRepository)
            : base(identityRepository)
        { }

        #endregion

        #region Actions

        public ActionResult Index()
        {
            return View(IdentityRepository.RoleManager.Roles.OrderBy(i => i.Name));
        }

        public ActionResult Create()
        {
            return View();
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (!ModelState.IsValid) return View();

            var role = new IdentityRole(roleViewModel.Name);

            IdentityResult result = await IdentityRepository.RoleManager.CreateAsync(role);

            IsResultNotSucceededAddModelError(result);

            if (result.Succeeded) return RedirectToAction("Index");

            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var role = await IdentityRepository.RoleManager.FindByIdAsync(id);

            if (role == null) return HttpNotFound();

            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };

            return View(roleModel);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(RoleViewModel roleModel)
        {
            if (!ModelState.IsValid) return View();

            IdentityRole role = await IdentityRepository.RoleManager.FindByIdAsync(roleModel.Id);

            role.Name = roleModel.Name;

            await IdentityRepository.RoleManager.UpdateAsync(role);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            IdentityRole role = await IdentityRepository.RoleManager.FindByIdAsync(id);

            if (role == null) return HttpNotFound();

            return View(role);
        }

        [Authorizer(Roles = "Administrators")]
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (!ModelState.IsValid) return View();

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            IdentityRole role = await IdentityRepository.RoleManager.FindByIdAsync(id);

            if (role == null) return HttpNotFound();

            IdentityResult result = await IdentityRepository.RoleManager.DeleteAsync(role);

            IsResultNotSucceededAddModelError(result);

            if (result.Succeeded) return RedirectToAction("Index");

            return View();
        }

        #endregion
    }
}

_6tactics.Cms.Web/Views/Shared/Admin/_ActionsMenu.cshtml
@using _6tactics.Cms.Web.App_Logic
@model dynamic

@{
    var actionName = "";
    var addingForElement = "";
    string displayType = "";

    if (ElementsVisibilityUtility.IsCreatePage || ElementsVisibilityUtility.IsEditPage)
    {
        var selectedDisplayType = Model.ContentItemViewModel.DisplayType;
        displayType = selectedDisplayType != null ? string.Concat(" / ", selectedDisplayType.ToUpper()) : "";
    }

    if (ElementsVisibilityUtility.IsCreatePage)
    {
        actionName = "CREATE CHILD FOR:";
        addingForElement = string.Concat(Model.CreateEditDataViewModel.SelectedTitle.ToUpper(), " (", Model.ContentItemViewModel.ContentType.ToString().ToUpper(), displayType, ")");
    }
    else if (ElementsVisibilityUtility.IsEditPage)
    {
        actionName = "EDIT:";
        addingForElement = string.Concat(Model.ContentItemViewModel.Title.ToUpper(), " (", Model.ContentItemViewModel.ContentType.ToString().ToUpper(), displayType, ")");
    }
    else if (ElementsVisibilityUtility.IsPluginsPage)
    {
        actionName = "PLUGINS";
    }
    else if (ElementsVisibilityUtility.IsSetupPage)
    {
        actionName = "SETUP";
    }
    else if (ElementsVisibilityUtility.IsDetailsPage)
    {
        var selectedDisplayType = Model.DisplayType;
        displayType = selectedDisplayType != null ? string.Concat(" / ", selectedDisplayType.ToUpper()) : "";
        
        actionName = "DETAILS:";
        addingForElement = string.Concat(Model.Title.ToUpper(), " (", Model.ContentType.ToString().ToUpper(), displayType, ")");
    }
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container actions-menu">

        <div class="navbar-header">
            <span class="actions-menu-title pull-left"><b>ADMIN</b> / @actionName @addingForElement</span>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right top-menu-items" style="color: white; ">

                @if (ElementsVisibilityUtility.IsCreatePage)
                {
                    <li>
                        <div style="margin-top: 12px;">
                            <div class="pull-left" style="margin-top: -14px; margin-left: 3px; margin-right: 10px;">
                                <label style="margin-top: 10px; padding-right: 5px;" class="pull-left" for="CreateEditDataViewModel_IsCreateChild">Automatically create child</label>
                                    
                                <input checked="checked" data-val="true" data-val-required="The IsCreateChild field is required." id="CreateEditDataViewModel_IsCreateChild" name="CreateEditDataViewModel.IsCreateChild" type="checkbox" value="true">
                                <input name="CreateEditDataViewModel.IsCreateChild" type="hidden" value="false">
                            </div>
                        </div>
                    </li>
                    <li>
                        <input type="submit" value="Create" class="btn btn-danger" />
                    </li>
                }
                @if (ElementsVisibilityUtility.IsEditPage)
                {
                    <li>
                        <input type="submit" value="Update" class="btn btn-danger" />
                    </li>
                }
                @*@if (ElementsVisibilityUtility.IsPluginsPage)
                {
                    <li>
                        <input type="submit" value="Save plugin settings" class="btn btn-danger" />
                    </li>
                }*@
                @if (ElementsVisibilityUtility.IsSetupPage)
                {
                    <li>
                        <input type="submit" value="Save setup" class="btn btn-danger" />
                    </li>
                }
                @if (ElementsVisibilityUtility.IsDetailsPage)
                {
                    <li>
                        <div class="details-actions">
                            <a class="action-menu-href" href="@Url.Action("Edit", "Admin", new{id = Model.Id})">
                                <h4><span class="label label-danger link-link"><span class="glyphicon glyphicon-edit"></span><span class="link-link-text"> Edit</span></span></h4>
                            </a>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

_6tactics.Cms.Web/Views/Shared/Admin/_AdminMenu.cshtml
@using Microsoft.AspNet.Identity
@using _6tactics.Cms.Core.Entities
@using _6tactics.Cms.Web.App_Logic
@model dynamic

@{
    var homePageSelected = "";
    var prioritiesPageSelected = "";
    var setupPageSelected = "";
    var fileManagerPageSelected = "";
    var pluginManagerPageSelected = "";

    var createPageSelected = "";
    var editPageSelected = "";
    var detailsPageSelected = "";

    var accountMenu = "";
    var accountManage = "";
    var usersAdministration = "";
    var rolesAdministration = "";


    if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsHomePage)
    {
        homePageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsPrioritiePage)
    {
        prioritiesPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsCreatePage)
    {
        createPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsEditPage)
    {
        editPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsDetailsPage)
    {
        detailsPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerSetup && ElementsVisibilityUtility.IsHomePage)
    {
        setupPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerPluginsManager && ElementsVisibilityUtility.IsHomePage)
    {
        pluginManagerPageSelected = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerFileManager && ElementsVisibilityUtility.IsHomePage)
    {
        fileManagerPageSelected = "active";
    }
    else
    {
        homePageSelected = "";
        prioritiesPageSelected = "";
        pluginManagerPageSelected = "";
        setupPageSelected = "";
        fileManagerPageSelected = "";
    }

    if (ElementsVisibilityUtility.IsCurrentControllerManage)
    {
        accountManage = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerUserAdministration)
    {
        usersAdministration = "active";
    }
    else if (ElementsVisibilityUtility.IsCurrentControllerRolesAdministration)
    {
        rolesAdministration = "active";
    }
    else
    {
        accountManage = "";
        usersAdministration = "";
        rolesAdministration = "";
    }

    if (ElementsVisibilityUtility.IsCurrentControllerManage ||
        ElementsVisibilityUtility.IsCurrentControllerUserAdministration ||
        ElementsVisibilityUtility.IsCurrentControllerRolesAdministration)
    {
        accountMenu = "active";
    }
    else
    {
        accountMenu = "";
    }
}

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid navbar-container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button style="height: 20px !important; border: 0;" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class=" nav navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="@homePageSelected">
                        <a href="@Url.Action("Index", "Admin")">
                            <span class="glyphicon glyphicon-tasks navbar-icon-margin"></span> Dashboard
                        </a>
                    </li>
                    if (Model != null && ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsHomePage)
                    {
                        @Html.Partial("Admin/_TreeViewActions", (ContentItem)Model)

                    }

                    <li class="@prioritiesPageSelected">
                        <a href="@Url.Action("Priorities", "Admin")">
                            <span class="glyphicon glyphicon-sort navbar-icon-margin"></span> Priorities
                        </a>
                    </li>
                    if (Model != null && ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsPrioritiePage)
                    {
                        @Html.Partial("Admin/_TreeViewActions", (ContentItem)Model)
                    }

                    if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsCreatePage)
                    {
                        <li class="@createPageSelected">
                            <a><span class="glyphicon glyphicon-new-window navbar-icon-margin"></span>Create</a>
                        </li>

                        <li>
                            <div>
                                <div class="label navbar-label-wrapper navbar-subitems-active pull-left">
                                    <label class="pull-left" for="CreateEditDataViewModel_IsCreateChild">Automatically create <b>child</b></label>
                                    <input checked="checked" id="CreateEditDataViewModel_IsCreateChild" name="CreateEditDataViewModel.IsCreateChild" type="checkbox" value="true">
                                    <input name="CreateEditDataViewModel.IsCreateChild" type="hidden" value="false">
                                </div>
                            </div>
                        </li>
                        <li>
                            <input type="submit" value="Create" class="btn btn-danger navbar-action-button" />
                        </li>
                    }
                    if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsEditPage)
                    {
                        <li class="@editPageSelected">
                            <a><span class="glyphicon glyphicon-edit navbar-icon-margin"></span>Edit</a>
                        </li>
                        <li>
                            <input type="submit" value="Update" class="btn btn-danger navbar-action-button" />
                        </li>
                    }
                    if (ElementsVisibilityUtility.IsCurrentControllerAdmin && ElementsVisibilityUtility.IsDetailsPage)
                    {
                        <li class="@detailsPageSelected">
                            <a><span class="glyphicon glyphicon-log-out navbar-icon-margin"></span>Details</a>
                        </li>
                    }

                    <li class="@fileManagerPageSelected">
                        <a href="@Url.Action("Index", "FileManager")">
                            <span class="glyphicon glyphicon-folder-open navbar-icon-margin"></span> File Manager
                        </a>
                    </li>
                    if (ElementsVisibilityUtility.IsCurrentControllerFileManager && ElementsVisibilityUtility.IsHomePage)
                    {
                        <li>
                            <button id="upload-edit-files" class="btn btn-danger navbar-action-button">Upload/Update</button>
                        </li>
                    }
                    <li class="@pluginManagerPageSelected">
                        <a href="@Url.Action("Index", "PluginsManager")">
                            <span class="glyphicon glyphicon-paperclip navbar-icon-margin"></span> Plugins Manager
                        </a>
                    </li>
                    @*if (ElementsVisibilityUtility.IsPluginsPage)
                        {
                            <li class="navbar-submit-button">
                                <input type="submit" value="Save plugin settings" class="btn btn-danger navbar-action-button" />
                            </li>
                        }*@
                    <li class="@setupPageSelected">
                        <a href="@Url.Action("Index", "Setup")">
                            <span class="glyphicon glyphicon-cog navbar-icon-margin"></span> Setup
                        </a>
                    </li>
                    if (ElementsVisibilityUtility.IsCurrentControllerSetup && ElementsVisibilityUtility.IsHomePage)
                    {
                        <li class="navbar-submit-button">
                            <input type="submit" value="Save setup" class="btn btn-danger navbar-action-button" />
                        </li>
                    }
                }
            </ul>



            <ul class="nav navbar-nav navbar-right" style="margin-right: 0;">
                <li class="dropdown pages-list @accountMenu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdown-language-title">
                        <span class="glyphicon glyphicon-user navbar-icon-margin"></span> @User.Identity.GetUserName()
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li class="@accountManage"><a href="@Url.Action("Index", "Manage")">Manage your account</a></li>
                        <li class="@usersAdministration"><a href="@Url.Action("Index", "UserAdministration")">Users administration</a></li>
                        <li class="@rolesAdministration"><a href="@Url.Action("Index", "RolesAdministration")">Roles administration</a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:document.getElementById('logoutForm').submit()">
                        <span class="glyphicon glyphicon-off navbar-icon-margin"></span> Log off
                    </a>
                </li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</div>